### PR TITLE
Get to hello world.

### PR DESCRIPTION
**Pull request by jmm**
Re: https://github.com/substack/node-browserify/issues/1161

There's a lot of messy stuff right now, internally, with matching up values passed to methods like `b.external()` with values coming from other places. This is in the nature of a band aid. It gets this test case to hello world. But it's not necessarily a robust, general purpose solution. There may still be fundamental issues lurking that need to be fixed.

### CODE REVIEW

**Comment by aldendaniels** [comment]
Ah! That does indeed got the Hello World version working. 

I'll give this a shot in my full project and see if this keeps working. I previously experimented with something similar without success, but I'm not sure it was exactly the same.

**Comment by aldendaniels** [comment]
@jmm - Unfortunately, your pessimistic prediction was correct. :/ This still isn't working in my larger project. 

Do you think it's worth continued troubleshooting (I can beef up this example until I get it to break as well), or is `.external()` too broken at this time to justify continued research?

**Comment by jmm** [comment]
@aldendaniels It's tough to say. With the state things are in, it's a game of whack a mole.

Where you're `require()`'ing things in bundle A that you want to exclude from bundle A and include in bundle B, are they all being `require()`'d using module style paths, as opposed to relative (`./` `../`) or absolute paths?

**Comment by aldendaniels** [comment]
@jmm - In my code I only do `require('module-name')` but many of the modules use relative path includes internally, so both need to be handled.

**Comment by aldendaniels** [comment]
Alternatively - is there a better way to accomplish this?

My motivation that caused me to start exploring this initially was source map performance:
1. I want to have source maps for my own code (very important as I'm using the babel transpiler).
2. Generating source maps for vendor code causes Chrome to freeze while it parses the source maps. I'm using some large libraries: React, Highcharts, Bluebird, jQuery.

If I can't get this to work, I might instead just load these large libraries via `<script>` tags and then shim them. Hopefully shimming won't turn into its own nightmare...

**Comment by jmm** [comment]
@aldendaniels 

> In my code I only do `require('module-name')` but many of the modules use relative path includes internally, so both need to be handled.

You should ideally only have to worry about the modules actually referenced by `require()` calls though. If you can stop those from being parsed for dependencies it'll be the other bundle's problem. The way things are right now I'm not finding a real elegant way to pull this off. I would eventually like to explore the idea of providing more hooks into this system.

I haven't had the chance to test this, but I started experimenting with the idea of using my [pathmodify](https://www.npmjs.com/package/pathmodify) plugin to do this. Even if it works it's hokier than I like, but I'm not sure there'd be a non-hokey way to do it right now (though there may be some other hokey ones).

``` js
var
  resolve = require('node-resolve'),
  pathmod = require('pathmodify');

mainBundle
  .plugin(pathmod(), {mods: [
    function (row) {
      if (! /^[\/.]/.test(row.id)) {
        var file = resolve.sync(row.id, {
          basedir: row.opts.filename || b._options.basedir
        });
        mainBundle.external(row.file);
        vendorBundle.require(row.file, {expose: row.id});
      }
    }
  ]})
```

**Comment by jmm** [comment]
> If I can't get this to work, I might instead just load these large libraries via `<script>` tags and then shim them. Hopefully shimming won't turn into its own nightmare...

Well it might be that the only tricky part about that is that you have to manually list those libraries somewhere instead of them just being part of your dependency graph. If they're proper CommonJS modules you won't need to shim them per se.

**Comment by aldendaniels** [comment]
So I actually got this to work in my main project like so:

``` javascript
mainBundle.on('file', function(file, id) {
  // Exclude descendents of node_modules from the main module.
  if (minimatch(file, '**/node_modules/**')) {
    mainBundle.external(file);
    mainBundle.external(id);
  }

  // Add top-level node modules to external bundle.
  var isNodeModuleImport = id.slice(0, 1) !== '.';
  var isTopLevelModule = file.split('/node_modules/').length === 2;
  if (isNodeModuleImport && isTopLevelModule) {
    externalBundle.require(file, {expose: id});
  }
});
```

The key is to ONLY `.require()` top-level node modules, but to `.external()` everything under `node_modules`.

**Comment by aldendaniels** [comment]
@jmm - Your "pathModify" solution might still be better if that works.

My solution is pretty limited - it works for `require('mymodule')` but fails for `require('mymodule/some/internal/file.js')`.

**Comment by jmm** [comment]
@aldendaniels I had a better idea about how to do it with pathmodify. Take a look at #5. That gives you access to the `id` (as in `require('id')`) and the resolved pathname in time to `.external()` it, without having to deal with resolving it yourself.

**Pull request merged**
